[theme]
base            = "dark"
primaryColor    = "#7C6AF7"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D27"
textColor       = "#FFFFFF"
font            = "sans serif"

[server]
headless        = true
enableCORS      = false

[browser]
gatherUsageStats = false
